# This file is for deployed lambda only
# it contains key properties specific to the server
[main]
env = dev
private_key_name = ..\..\..\custodian\config\dev_private_key.pem
location = ra
app_logs_root = ..\..\..\logs
shared_config_dir = ..\..\..\shared_config

# list of apps in the server and their path
# Used by config to find config files in ${app_name}/config
# path relative to CWD
[apps]
ami-mgmt : .